"use strict";
const API_URL="https://music-backend-production-10bd.up.railway.app";
const $=id=>document.getElementById(id),audio=$("audio"),fallback="https://via.placeholder.com/400/24242a/ffffff?text=Musicfy";
let tracks=[],current=-1,featured=null;
const clean=value=>String(value||"Untitled").replace(/\.[^/.]+$/,""),art=t=>t.artwork||fallback;
const saved=()=>{try{return JSON.parse(localStorage.getItem("musicfy-favorites")||"[]")}catch{return[]}},isFavorite=t=>saved().includes(String(t.id)),toggleFavorite=t=>{const ids=saved(),id=String(t.id),next=ids.includes(id)?ids.filter(x=>x!==id):[...ids,id];localStorage.setItem("musicfy-favorites",JSON.stringify(next));renderAll();updateFavoriteButton()};
function card(track,{artist=false}={}){const el=document.createElement("article");el.className="card"+(artist?" artist-card":"");el.innerHTML=`<img alt=""><div class="title"></div><div class="sub"></div>`;el.querySelector("img").src=art(track);el.querySelector(".title").textContent=clean(artist?track.artist:track.title);el.querySelector(".sub").textContent=artist?"Artist":track.artist||"Unknown artist";el.onclick=()=>artist?showArtist(track.artist):play(track);return el}
function trackRow(track){const row=document.createElement("article");row.className="track";row.innerHTML=`<img alt=""><div class="meta"><strong></strong><small></small></div><button class="like" aria-label="Favorite"></button>`;row.querySelector("img").src=art(track);row.querySelector("strong").textContent=clean(track.title);row.querySelector("small").textContent=[track.artist,track.album].filter(Boolean).join(" · ");const like=row.querySelector(".like");like.textContent=isFavorite(track)?"♥":"♡";like.classList.toggle("on",isFavorite(track));like.onclick=e=>{e.stopPropagation();toggleFavorite(track)};row.onclick=()=>play(track);return row}
function fill(id,items,fn){const box=$(id);box.replaceChildren();if(!items.length){box.innerHTML='<p class="empty">Nothing here yet.</p>';return}items.forEach(x=>box.append(fn(x)))}
function uniqueBy(key){return [...new Map(tracks.filter(t=>t[key]).map(t=>[t[key],t])).values()]}
function shuffle(list){return list.slice().sort(()=>Math.random()-.5)}
function renderHome(){const latest=tracks.slice(-10).reverse();fill("recentRow",latest,card);const seed=featured||tracks[0];const recommendations=shuffle(tracks.filter(t=>t.id!==seed?.id)).slice(0,8);fill("recommendationRow",recommendations,card);fill("albumRow",uniqueBy("album"),t=>{const c=card({...t,title:t.album});c.onclick=()=>showAlbum(t.album);return c});fill("artistRow",uniqueBy("artist"),t=>card(t,{artist:true}));if(featured){$("heroTitle").textContent=clean(featured.title);$("heroArtist").textContent=featured.artist||"Unknown artist"}}
function renderAll(){renderHome();fill("libraryList",tracks,trackRow);fill("albumsPage",uniqueBy("album"),t=>{const c=card({...t,title:t.album});c.onclick=()=>showAlbum(t.album);return c});fill("artistsPage",uniqueBy("artist"),t=>card(t,{artist:true}));fill("favoritesList",tracks.filter(isFavorite),trackRow)}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===id));document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===id));window.scrollTo(0,0)}
function showAlbum(name){fill("libraryList",tracks.filter(t=>t.album===name),trackRow);showPage("library")};function showArtist(name){fill("libraryList",tracks.filter(t=>t.artist===name),trackRow);showPage("library")}
function play(track){current=tracks.findIndex(t=>String(t.id)===String(track.id));if(current<0)return;audio.src=track.url;audio.play().catch(()=>{});$("songTitle").textContent=clean(track.title);$("songArtist").textContent=track.artist||"Unknown artist";$("playerArt").src=art(track);$("playerArt").hidden=false;$("play").textContent="❚❚";updateFavoriteButton()}
function updateFavoriteButton(){const t=tracks[current],b=$("favorite");b.textContent=t&&isFavorite(t)?"♥":"♡";b.classList.toggle("on",Boolean(t&&isFavorite(t)))}
function next(delta){if(!tracks.length)return;current=(current+delta+tracks.length)%tracks.length;play(tracks[current])}
$("play").onclick=()=>{if(!tracks.length)return;if(current<0)play(featured||tracks[0]);else if(audio.paused)audio.play().then(()=>$("play").textContent="❚❚");else audio.pause()};$("previous").onclick=()=>next(-1);$("next").onclick=()=>next(1);$("heroPlay").onclick=()=>featured&&play(featured);$("favorite").onclick=()=>tracks[current]&&toggleFavorite(tracks[current]);audio.onpause=()=>$("play").textContent="▶";audio.onplay=()=>$("play").textContent="❚❚";audio.onended=()=>next(1);audio.ontimeupdate=()=>{if(audio.duration){$("progress").value=audio.currentTime/audio.duration*100;$("currentTime").textContent=format(audio.currentTime)}};audio.onloadedmetadata=()=>$("duration").textContent=format(audio.duration);$("progress").oninput=e=>{if(audio.duration)audio.currentTime=audio.duration*e.target.value/100};function format(s){if(!Number.isFinite(s))return"0:00";return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,"0")}`}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>showPage(b.dataset.page));$("search").oninput=e=>{const q=e.target.value.toLowerCase().trim();fill("libraryList",tracks.filter(t=>[t.title,t.artist,t.album].some(v=>String(v||"").toLowerCase().includes(q))),trackRow);showPage("library")};
async function load(){try{const r=await fetch(`${API_URL}/api/library`);if(!r.ok)throw Error("Library unavailable");const data=await r.json();tracks=data.tracks||[];featured=tracks[Math.floor(Math.random()*tracks.length)]||null;renderAll()}catch(err){console.error(err);["recentRow","recommendationRow","albumRow","artistRow","libraryList","albumsPage","artistsPage","favoritesList"].forEach(id=>$(id).innerHTML='<p class="empty">Your library could not be loaded right now.</p>');$("heroArtist").textContent="Try again in a moment."}}
if("serviceWorker"in navigator)navigator.serviceWorker.register("/service-worker.js").catch(()=>{});load();
